<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Scottbass3\Harbor\Api\Endpoint;

class ExportScanData extends \Scottbass3\Harbor\Api\Runtime\Client\BaseEndpoint implements \Scottbass3\Harbor\Api\Runtime\Client\Endpoint
{
    use \Scottbass3\Harbor\Api\Runtime\Client\EndpointTrait;

    /**
     * Export scan data for selected projects.
     *
     * @param \Scottbass3\Harbor\Api\Model\ScanDataExportRequest $criteria         The criteria for the export
     * @param array                                              $headerParameters {
     *
     * @var string $X-Request-Id An unique ID for the request
     * @var string $X-Scan-Data-Type The type of scan data to export
     *             }
     */
    public function __construct(\Scottbass3\Harbor\Api\Model\ScanDataExportRequest $criteria, array $headerParameters = [])
    {
        $this->body = $criteria;
        $this->headerParameters = $headerParameters;
    }

    public function getMethod(): string
    {
        return 'POST';
    }

    public function getUri(): string
    {
        return '/export/cve';
    }

    public function getBody(\Symfony\Component\Serializer\SerializerInterface $serializer, $streamFactory = null): array
    {
        return $this->getSerializedBody($serializer);
    }

    public function getExtraHeaders(): array
    {
        return ['Accept' => ['application/json']];
    }

    protected function getHeadersOptionsResolver(): \Symfony\Component\OptionsResolver\OptionsResolver
    {
        $optionsResolver = parent::getHeadersOptionsResolver();
        $optionsResolver->setDefined(['X-Request-Id', 'X-Scan-Data-Type']);
        $optionsResolver->setRequired(['X-Scan-Data-Type']);
        $optionsResolver->setDefaults([]);
        $optionsResolver->addAllowedTypes('X-Request-Id', ['string']);
        $optionsResolver->addAllowedTypes('X-Scan-Data-Type', ['string']);

        return $optionsResolver;
    }

    /**
     * @return \Scottbass3\Harbor\Api\Model\ScanDataExportJob
     *
     * @throws \Scottbass3\Harbor\Api\Exception\ExportScanDataBadRequestException
     * @throws \Scottbass3\Harbor\Api\Exception\ExportScanDataUnauthorizedException
     * @throws \Scottbass3\Harbor\Api\Exception\ExportScanDataForbiddenException
     * @throws \Scottbass3\Harbor\Api\Exception\ExportScanDataNotFoundException
     * @throws \Scottbass3\Harbor\Api\Exception\ExportScanDataMethodNotAllowedException
     * @throws \Scottbass3\Harbor\Api\Exception\ExportScanDataConflictException
     * @throws \Scottbass3\Harbor\Api\Exception\ExportScanDataInternalServerErrorException
     * @throws \Scottbass3\Harbor\Api\Exception\UnexpectedStatusCodeException
     */
    protected function transformResponseBody(\Psr\Http\Message\ResponseInterface $response, \Symfony\Component\Serializer\SerializerInterface $serializer, ?string $contentType = null)
    {
        $status = $response->getStatusCode();
        $body = (string) $response->getBody();
        if (200 === $status) {
            return $serializer->deserialize($body, 'Scottbass3\Harbor\Api\Model\ScanDataExportJob', 'json');
        }
        if (400 === $status) {
            throw new \Scottbass3\Harbor\Api\Exception\ExportScanDataBadRequestException($serializer->deserialize($body, 'Scottbass3\Harbor\Api\Model\Errors', 'json'), $response);
        }
        if (401 === $status) {
            throw new \Scottbass3\Harbor\Api\Exception\ExportScanDataUnauthorizedException($serializer->deserialize($body, 'Scottbass3\Harbor\Api\Model\Errors', 'json'), $response);
        }
        if (403 === $status) {
            throw new \Scottbass3\Harbor\Api\Exception\ExportScanDataForbiddenException($serializer->deserialize($body, 'Scottbass3\Harbor\Api\Model\Errors', 'json'), $response);
        }
        if (404 === $status) {
            throw new \Scottbass3\Harbor\Api\Exception\ExportScanDataNotFoundException($serializer->deserialize($body, 'Scottbass3\Harbor\Api\Model\Errors', 'json'), $response);
        }
        if (405 === $status) {
            throw new \Scottbass3\Harbor\Api\Exception\ExportScanDataMethodNotAllowedException($serializer->deserialize($body, 'Scottbass3\Harbor\Api\Model\Errors', 'json'), $response);
        }
        if (409 === $status) {
            throw new \Scottbass3\Harbor\Api\Exception\ExportScanDataConflictException($serializer->deserialize($body, 'Scottbass3\Harbor\Api\Model\Errors', 'json'), $response);
        }
        if (500 === $status) {
            throw new \Scottbass3\Harbor\Api\Exception\ExportScanDataInternalServerErrorException($serializer->deserialize($body, 'Scottbass3\Harbor\Api\Model\Errors', 'json'), $response);
        }
        throw new \Scottbass3\Harbor\Api\Exception\UnexpectedStatusCodeException($status, $body);
    }

    public function getAuthenticationScopes(): array
    {
        return ['basic'];
    }
}
