<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Scottbass3\Harbor\Api\Endpoint;

class GetRepository extends \Scottbass3\Harbor\Api\Runtime\Client\BaseEndpoint implements \Scottbass3\Harbor\Api\Runtime\Client\Endpoint
{
    use \Scottbass3\Harbor\Api\Runtime\Client\EndpointTrait;
    protected $project_name;
    protected $repository_name;

    /**
     * Get the repository specified by name.
     *
     * @param string $projectName      The name of the project
     * @param string $repositoryName   The name of the repository. If it contains slash, encode it twice over with URL encoding. e.g. a/b -> a%2Fb -> a%252Fb
     * @param array  $headerParameters {
     *
     * @var string $X-Request-Id An unique ID for the request
     *             }
     */
    public function __construct(string $projectName, string $repositoryName, array $headerParameters = [])
    {
        $this->project_name = $projectName;
        $this->repository_name = $repositoryName;
        $this->headerParameters = $headerParameters;
    }

    public function getMethod(): string
    {
        return 'GET';
    }

    public function getUri(): string
    {
        return str_replace(['{project_name}', '{repository_name}'], [$this->project_name, $this->repository_name], '/projects/{project_name}/repositories/{repository_name}');
    }

    public function getBody(\Symfony\Component\Serializer\SerializerInterface $serializer, $streamFactory = null): array
    {
        return [[], null];
    }

    public function getExtraHeaders(): array
    {
        return ['Accept' => ['application/json']];
    }

    protected function getHeadersOptionsResolver(): \Symfony\Component\OptionsResolver\OptionsResolver
    {
        $optionsResolver = parent::getHeadersOptionsResolver();
        $optionsResolver->setDefined(['X-Request-Id']);
        $optionsResolver->setRequired([]);
        $optionsResolver->setDefaults([]);
        $optionsResolver->addAllowedTypes('X-Request-Id', ['string']);

        return $optionsResolver;
    }

    /**
     * @return \Scottbass3\Harbor\Api\Model\Repository
     *
     * @throws \Scottbass3\Harbor\Api\Exception\GetRepositoryBadRequestException
     * @throws \Scottbass3\Harbor\Api\Exception\GetRepositoryUnauthorizedException
     * @throws \Scottbass3\Harbor\Api\Exception\GetRepositoryForbiddenException
     * @throws \Scottbass3\Harbor\Api\Exception\GetRepositoryNotFoundException
     * @throws \Scottbass3\Harbor\Api\Exception\GetRepositoryInternalServerErrorException
     * @throws \Scottbass3\Harbor\Api\Exception\UnexpectedStatusCodeException
     */
    protected function transformResponseBody(\Psr\Http\Message\ResponseInterface $response, \Symfony\Component\Serializer\SerializerInterface $serializer, ?string $contentType = null)
    {
        $status = $response->getStatusCode();
        $body = (string) $response->getBody();
        if (200 === $status) {
            return $serializer->deserialize($body, 'Scottbass3\Harbor\Api\Model\Repository', 'json');
        }
        if (400 === $status) {
            throw new \Scottbass3\Harbor\Api\Exception\GetRepositoryBadRequestException($serializer->deserialize($body, 'Scottbass3\Harbor\Api\Model\Errors', 'json'), $response);
        }
        if (401 === $status) {
            throw new \Scottbass3\Harbor\Api\Exception\GetRepositoryUnauthorizedException($serializer->deserialize($body, 'Scottbass3\Harbor\Api\Model\Errors', 'json'), $response);
        }
        if (403 === $status) {
            throw new \Scottbass3\Harbor\Api\Exception\GetRepositoryForbiddenException($serializer->deserialize($body, 'Scottbass3\Harbor\Api\Model\Errors', 'json'), $response);
        }
        if (404 === $status) {
            throw new \Scottbass3\Harbor\Api\Exception\GetRepositoryNotFoundException($serializer->deserialize($body, 'Scottbass3\Harbor\Api\Model\Errors', 'json'), $response);
        }
        if (500 === $status) {
            throw new \Scottbass3\Harbor\Api\Exception\GetRepositoryInternalServerErrorException($serializer->deserialize($body, 'Scottbass3\Harbor\Api\Model\Errors', 'json'), $response);
        }
        throw new \Scottbass3\Harbor\Api\Exception\UnexpectedStatusCodeException($status, $body);
    }

    public function getAuthenticationScopes(): array
    {
        return ['basic'];
    }
}
