<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Scottbass3\Harbor\Api\Normalizer;

use Scottbass3\Harbor\Api\Runtime\Normalizer\CheckArray;
use Scottbass3\Harbor\Api\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class ArtifactNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;

    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \Scottbass3\Harbor\Api\Model\Artifact::class;
    }

    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && get_class($data) === \Scottbass3\Harbor\Api\Model\Artifact::class;
    }

    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \Scottbass3\Harbor\Api\Model\Artifact();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('id', $data) && $data['id'] !== null) {
            $object->setId($data['id']);
        } elseif (\array_key_exists('id', $data) && $data['id'] === null) {
            $object->setId(null);
        }
        if (\array_key_exists('type', $data) && $data['type'] !== null) {
            $object->setType($data['type']);
        } elseif (\array_key_exists('type', $data) && $data['type'] === null) {
            $object->setType(null);
        }
        if (\array_key_exists('media_type', $data) && $data['media_type'] !== null) {
            $object->setMediaType($data['media_type']);
        } elseif (\array_key_exists('media_type', $data) && $data['media_type'] === null) {
            $object->setMediaType(null);
        }
        if (\array_key_exists('manifest_media_type', $data) && $data['manifest_media_type'] !== null) {
            $object->setManifestMediaType($data['manifest_media_type']);
        } elseif (\array_key_exists('manifest_media_type', $data) && $data['manifest_media_type'] === null) {
            $object->setManifestMediaType(null);
        }
        if (\array_key_exists('project_id', $data) && $data['project_id'] !== null) {
            $object->setProjectId($data['project_id']);
        } elseif (\array_key_exists('project_id', $data) && $data['project_id'] === null) {
            $object->setProjectId(null);
        }
        if (\array_key_exists('repository_id', $data) && $data['repository_id'] !== null) {
            $object->setRepositoryId($data['repository_id']);
        } elseif (\array_key_exists('repository_id', $data) && $data['repository_id'] === null) {
            $object->setRepositoryId(null);
        }
        if (\array_key_exists('digest', $data) && $data['digest'] !== null) {
            $object->setDigest($data['digest']);
        } elseif (\array_key_exists('digest', $data) && $data['digest'] === null) {
            $object->setDigest(null);
        }
        if (\array_key_exists('size', $data) && $data['size'] !== null) {
            $object->setSize($data['size']);
        } elseif (\array_key_exists('size', $data) && $data['size'] === null) {
            $object->setSize(null);
        }
        if (\array_key_exists('icon', $data) && $data['icon'] !== null) {
            $object->setIcon($data['icon']);
        } elseif (\array_key_exists('icon', $data) && $data['icon'] === null) {
            $object->setIcon(null);
        }
        if (\array_key_exists('push_time', $data) && $data['push_time'] !== null) {
            $object->setPushTime(\DateTime::createFromFormat('Y-m-d\TH:i:s.vp', $data['push_time']));
        } elseif (\array_key_exists('push_time', $data) && $data['push_time'] === null) {
            $object->setPushTime(null);
        }
        if (\array_key_exists('pull_time', $data) && $data['pull_time'] !== null) {
            $object->setPullTime(\DateTime::createFromFormat('Y-m-d\TH:i:s.vp', $data['pull_time']));
        } elseif (\array_key_exists('pull_time', $data) && $data['pull_time'] === null) {
            $object->setPullTime(null);
        }
        if (\array_key_exists('extra_attrs', $data) && $data['extra_attrs'] !== null) {
            $values = new \ArrayObject([], \ArrayObject::ARRAY_AS_PROPS);
            foreach ($data['extra_attrs'] as $key => $value) {
                $values[$key] = $value;
            }
            $object->setExtraAttrs($values);
        } elseif (\array_key_exists('extra_attrs', $data) && $data['extra_attrs'] === null) {
            $object->setExtraAttrs(null);
        }
        if (\array_key_exists('annotations', $data) && $data['annotations'] !== null) {
            $values_1 = new \ArrayObject([], \ArrayObject::ARRAY_AS_PROPS);
            foreach ($data['annotations'] as $key_1 => $value_1) {
                $values_1[$key_1] = $value_1;
            }
            $object->setAnnotations($values_1);
        } elseif (\array_key_exists('annotations', $data) && $data['annotations'] === null) {
            $object->setAnnotations(null);
        }
        if (\array_key_exists('references', $data) && $data['references'] !== null) {
            $values_2 = [];
            foreach ($data['references'] as $value_2) {
                $values_2[] = $this->denormalizer->denormalize($value_2, \Scottbass3\Harbor\Api\Model\Reference::class, 'json', $context);
            }
            $object->setReferences($values_2);
        } elseif (\array_key_exists('references', $data) && $data['references'] === null) {
            $object->setReferences(null);
        }
        if (\array_key_exists('tags', $data) && $data['tags'] !== null) {
            $values_3 = [];
            foreach ($data['tags'] as $value_3) {
                $values_3[] = $this->denormalizer->denormalize($value_3, \Scottbass3\Harbor\Api\Model\Tag::class, 'json', $context);
            }
            $object->setTags($values_3);
        } elseif (\array_key_exists('tags', $data) && $data['tags'] === null) {
            $object->setTags(null);
        }
        if (\array_key_exists('addition_links', $data) && $data['addition_links'] !== null) {
            $values_4 = new \ArrayObject([], \ArrayObject::ARRAY_AS_PROPS);
            foreach ($data['addition_links'] as $key_2 => $value_4) {
                $values_4[$key_2] = $this->denormalizer->denormalize($value_4, \Scottbass3\Harbor\Api\Model\AdditionLink::class, 'json', $context);
            }
            $object->setAdditionLinks($values_4);
        } elseif (\array_key_exists('addition_links', $data) && $data['addition_links'] === null) {
            $object->setAdditionLinks(null);
        }
        if (\array_key_exists('labels', $data) && $data['labels'] !== null) {
            $values_5 = [];
            foreach ($data['labels'] as $value_5) {
                $values_5[] = $this->denormalizer->denormalize($value_5, \Scottbass3\Harbor\Api\Model\Label::class, 'json', $context);
            }
            $object->setLabels($values_5);
        } elseif (\array_key_exists('labels', $data) && $data['labels'] === null) {
            $object->setLabels(null);
        }
        if (\array_key_exists('scan_overview', $data) && $data['scan_overview'] !== null) {
            $values_6 = new \ArrayObject([], \ArrayObject::ARRAY_AS_PROPS);
            foreach ($data['scan_overview'] as $key_3 => $value_6) {
                $values_6[$key_3] = $this->denormalizer->denormalize($value_6, \Scottbass3\Harbor\Api\Model\NativeReportSummary::class, 'json', $context);
            }
            $object->setScanOverview($values_6);
        } elseif (\array_key_exists('scan_overview', $data) && $data['scan_overview'] === null) {
            $object->setScanOverview(null);
        }
        if (\array_key_exists('accessories', $data) && $data['accessories'] !== null) {
            $values_7 = [];
            foreach ($data['accessories'] as $value_7) {
                $values_7[] = $this->denormalizer->denormalize($value_7, \Scottbass3\Harbor\Api\Model\Accessory::class, 'json', $context);
            }
            $object->setAccessories($values_7);
        } elseif (\array_key_exists('accessories', $data) && $data['accessories'] === null) {
            $object->setAccessories(null);
        }

        return $object;
    }

    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        $dataArray = [];
        if ($data->isInitialized('id') && null !== $data->getId()) {
            $dataArray['id'] = $data->getId();
        }
        if ($data->isInitialized('type') && null !== $data->getType()) {
            $dataArray['type'] = $data->getType();
        }
        if ($data->isInitialized('mediaType') && null !== $data->getMediaType()) {
            $dataArray['media_type'] = $data->getMediaType();
        }
        if ($data->isInitialized('manifestMediaType') && null !== $data->getManifestMediaType()) {
            $dataArray['manifest_media_type'] = $data->getManifestMediaType();
        }
        if ($data->isInitialized('projectId') && null !== $data->getProjectId()) {
            $dataArray['project_id'] = $data->getProjectId();
        }
        if ($data->isInitialized('repositoryId') && null !== $data->getRepositoryId()) {
            $dataArray['repository_id'] = $data->getRepositoryId();
        }
        if ($data->isInitialized('digest') && null !== $data->getDigest()) {
            $dataArray['digest'] = $data->getDigest();
        }
        if ($data->isInitialized('size') && null !== $data->getSize()) {
            $dataArray['size'] = $data->getSize();
        }
        if ($data->isInitialized('icon') && null !== $data->getIcon()) {
            $dataArray['icon'] = $data->getIcon();
        }
        if ($data->isInitialized('pushTime') && null !== $data->getPushTime()) {
            $dataArray['push_time'] = $data->getPushTime()->format('Y-m-d\TH:i:s.vp');
        }
        if ($data->isInitialized('pullTime') && null !== $data->getPullTime()) {
            $dataArray['pull_time'] = $data->getPullTime()->format('Y-m-d\TH:i:s.vp');
        }
        if ($data->isInitialized('extraAttrs') && null !== $data->getExtraAttrs()) {
            $values = [];
            foreach ($data->getExtraAttrs() as $key => $value) {
                $values[$key] = $value;
            }
            $dataArray['extra_attrs'] = $values;
        }
        if ($data->isInitialized('annotations') && null !== $data->getAnnotations()) {
            $values_1 = [];
            foreach ($data->getAnnotations() as $key_1 => $value_1) {
                $values_1[$key_1] = $value_1;
            }
            $dataArray['annotations'] = $values_1;
        }
        if ($data->isInitialized('references') && null !== $data->getReferences()) {
            $values_2 = [];
            foreach ($data->getReferences() as $value_2) {
                $values_2[] = $this->normalizer->normalize($value_2, 'json', $context);
            }
            $dataArray['references'] = $values_2;
        }
        if ($data->isInitialized('tags') && null !== $data->getTags()) {
            $values_3 = [];
            foreach ($data->getTags() as $value_3) {
                $values_3[] = $this->normalizer->normalize($value_3, 'json', $context);
            }
            $dataArray['tags'] = $values_3;
        }
        if ($data->isInitialized('additionLinks') && null !== $data->getAdditionLinks()) {
            $values_4 = [];
            foreach ($data->getAdditionLinks() as $key_2 => $value_4) {
                $values_4[$key_2] = $this->normalizer->normalize($value_4, 'json', $context);
            }
            $dataArray['addition_links'] = $values_4;
        }
        if ($data->isInitialized('labels') && null !== $data->getLabels()) {
            $values_5 = [];
            foreach ($data->getLabels() as $value_5) {
                $values_5[] = $this->normalizer->normalize($value_5, 'json', $context);
            }
            $dataArray['labels'] = $values_5;
        }
        if ($data->isInitialized('scanOverview') && null !== $data->getScanOverview()) {
            $values_6 = [];
            foreach ($data->getScanOverview() as $key_3 => $value_6) {
                $values_6[$key_3] = $this->normalizer->normalize($value_6, 'json', $context);
            }
            $dataArray['scan_overview'] = $values_6;
        }
        if ($data->isInitialized('accessories') && null !== $data->getAccessories()) {
            $values_7 = [];
            foreach ($data->getAccessories() as $value_7) {
                $values_7[] = $this->normalizer->normalize($value_7, 'json', $context);
            }
            $dataArray['accessories'] = $values_7;
        }

        return $dataArray;
    }

    public function getSupportedTypes(?string $format = null): array
    {
        return [\Scottbass3\Harbor\Api\Model\Artifact::class => false];
    }
}
