<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Harbor\Api\Normalizer;

use Flownative\Harbor\Api\Runtime\Normalizer\CheckArray;
use Flownative\Harbor\Api\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

if (!class_exists(Kernel::class) or (Kernel::MAJOR_VERSION >= 7 or Kernel::MAJOR_VERSION === 6 and Kernel::MINOR_VERSION === 4)) {
    class ProjectMemberEntityNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
        {
            return $type === 'Flownative\\Harbor\\Api\\Model\\ProjectMemberEntity';
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === 'Flownative\\Harbor\\Api\\Model\\ProjectMemberEntity';
        }

        public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Flownative\Harbor\Api\Model\ProjectMemberEntity();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('id', $data)) {
                $object->setId($data['id']);
            }
            if (\array_key_exists('project_id', $data)) {
                $object->setProjectId($data['project_id']);
            }
            if (\array_key_exists('entity_name', $data)) {
                $object->setEntityName($data['entity_name']);
            }
            if (\array_key_exists('role_name', $data)) {
                $object->setRoleName($data['role_name']);
            }
            if (\array_key_exists('role_id', $data)) {
                $object->setRoleId($data['role_id']);
            }
            if (\array_key_exists('entity_id', $data)) {
                $object->setEntityId($data['entity_id']);
            }
            if (\array_key_exists('entity_type', $data)) {
                $object->setEntityType($data['entity_type']);
            }

            return $object;
        }

        public function normalize(mixed $object, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
        {
            $data = [];
            if ($object->isInitialized('id') && null !== $object->getId()) {
                $data['id'] = $object->getId();
            }
            if ($object->isInitialized('projectId') && null !== $object->getProjectId()) {
                $data['project_id'] = $object->getProjectId();
            }
            if ($object->isInitialized('entityName') && null !== $object->getEntityName()) {
                $data['entity_name'] = $object->getEntityName();
            }
            if ($object->isInitialized('roleName') && null !== $object->getRoleName()) {
                $data['role_name'] = $object->getRoleName();
            }
            if ($object->isInitialized('roleId') && null !== $object->getRoleId()) {
                $data['role_id'] = $object->getRoleId();
            }
            if ($object->isInitialized('entityId') && null !== $object->getEntityId()) {
                $data['entity_id'] = $object->getEntityId();
            }
            if ($object->isInitialized('entityType') && null !== $object->getEntityType()) {
                $data['entity_type'] = $object->getEntityType();
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return ['Flownative\\Harbor\\Api\\Model\\ProjectMemberEntity' => false];
        }
    }
} else {
    class ProjectMemberEntityNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization($data, $type, ?string $format = null, array $context = []): bool
        {
            return $type === 'Flownative\\Harbor\\Api\\Model\\ProjectMemberEntity';
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === 'Flownative\\Harbor\\Api\\Model\\ProjectMemberEntity';
        }

        public function denormalize($data, $type, $format = null, array $context = [])
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Flownative\Harbor\Api\Model\ProjectMemberEntity();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('id', $data)) {
                $object->setId($data['id']);
            }
            if (\array_key_exists('project_id', $data)) {
                $object->setProjectId($data['project_id']);
            }
            if (\array_key_exists('entity_name', $data)) {
                $object->setEntityName($data['entity_name']);
            }
            if (\array_key_exists('role_name', $data)) {
                $object->setRoleName($data['role_name']);
            }
            if (\array_key_exists('role_id', $data)) {
                $object->setRoleId($data['role_id']);
            }
            if (\array_key_exists('entity_id', $data)) {
                $object->setEntityId($data['entity_id']);
            }
            if (\array_key_exists('entity_type', $data)) {
                $object->setEntityType($data['entity_type']);
            }

            return $object;
        }

        /**
         * @return array|string|int|float|bool|\ArrayObject|null
         */
        public function normalize($object, $format = null, array $context = [])
        {
            $data = [];
            if ($object->isInitialized('id') && null !== $object->getId()) {
                $data['id'] = $object->getId();
            }
            if ($object->isInitialized('projectId') && null !== $object->getProjectId()) {
                $data['project_id'] = $object->getProjectId();
            }
            if ($object->isInitialized('entityName') && null !== $object->getEntityName()) {
                $data['entity_name'] = $object->getEntityName();
            }
            if ($object->isInitialized('roleName') && null !== $object->getRoleName()) {
                $data['role_name'] = $object->getRoleName();
            }
            if ($object->isInitialized('roleId') && null !== $object->getRoleId()) {
                $data['role_id'] = $object->getRoleId();
            }
            if ($object->isInitialized('entityId') && null !== $object->getEntityId()) {
                $data['entity_id'] = $object->getEntityId();
            }
            if ($object->isInitialized('entityType') && null !== $object->getEntityType()) {
                $data['entity_type'] = $object->getEntityType();
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return ['Flownative\\Harbor\\Api\\Model\\ProjectMemberEntity' => false];
        }
    }
}
