<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Scottbass3\Harbor\Api\Normalizer;

use Scottbass3\Harbor\Api\Runtime\Normalizer\CheckArray;
use Scottbass3\Harbor\Api\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class ScannerCapabilityNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;

    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \Scottbass3\Harbor\Api\Model\ScannerCapability::class;
    }

    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && get_class($data) === \Scottbass3\Harbor\Api\Model\ScannerCapability::class;
    }

    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \Scottbass3\Harbor\Api\Model\ScannerCapability();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('consumes_mime_types', $data) && $data['consumes_mime_types'] !== null) {
            $values = [];
            foreach ($data['consumes_mime_types'] as $value) {
                $values[] = $value;
            }
            $object->setConsumesMimeTypes($values);
        } elseif (\array_key_exists('consumes_mime_types', $data) && $data['consumes_mime_types'] === null) {
            $object->setConsumesMimeTypes(null);
        }
        if (\array_key_exists('produces_mime_types', $data) && $data['produces_mime_types'] !== null) {
            $values_1 = [];
            foreach ($data['produces_mime_types'] as $value_1) {
                $values_1[] = $value_1;
            }
            $object->setProducesMimeTypes($values_1);
        } elseif (\array_key_exists('produces_mime_types', $data) && $data['produces_mime_types'] === null) {
            $object->setProducesMimeTypes(null);
        }

        return $object;
    }

    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        $dataArray = [];
        if ($data->isInitialized('consumesMimeTypes') && null !== $data->getConsumesMimeTypes()) {
            $values = [];
            foreach ($data->getConsumesMimeTypes() as $value) {
                $values[] = $value;
            }
            $dataArray['consumes_mime_types'] = $values;
        }
        if ($data->isInitialized('producesMimeTypes') && null !== $data->getProducesMimeTypes()) {
            $values_1 = [];
            foreach ($data->getProducesMimeTypes() as $value_1) {
                $values_1[] = $value_1;
            }
            $dataArray['produces_mime_types'] = $values_1;
        }

        return $dataArray;
    }

    public function getSupportedTypes(?string $format = null): array
    {
        return [\Scottbass3\Harbor\Api\Model\ScannerCapability::class => false];
    }
}
