<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Harbor\Api\Normalizer;

use Flownative\Harbor\Api\Runtime\Normalizer\CheckArray;
use Flownative\Harbor\Api\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class SearchNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;

    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \Flownative\Harbor\Api\Model\Search::class;
    }

    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && get_class($data) === \Flownative\Harbor\Api\Model\Search::class;
    }

    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \Flownative\Harbor\Api\Model\Search();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('project', $data) && $data['project'] !== null) {
            $values = [];
            foreach ($data['project'] as $value) {
                $values[] = $this->denormalizer->denormalize($value, \Flownative\Harbor\Api\Model\Project::class, 'json', $context);
            }
            $object->setProject($values);
        } elseif (\array_key_exists('project', $data) && $data['project'] === null) {
            $object->setProject(null);
        }
        if (\array_key_exists('repository', $data) && $data['repository'] !== null) {
            $values_1 = [];
            foreach ($data['repository'] as $value_1) {
                $values_1[] = $this->denormalizer->denormalize($value_1, \Flownative\Harbor\Api\Model\SearchRepository::class, 'json', $context);
            }
            $object->setRepository($values_1);
        } elseif (\array_key_exists('repository', $data) && $data['repository'] === null) {
            $object->setRepository(null);
        }

        return $object;
    }

    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        $dataArray = [];
        if ($data->isInitialized('project') && null !== $data->getProject()) {
            $values = [];
            foreach ($data->getProject() as $value) {
                $values[] = $this->normalizer->normalize($value, 'json', $context);
            }
            $dataArray['project'] = $values;
        }
        if ($data->isInitialized('repository') && null !== $data->getRepository()) {
            $values_1 = [];
            foreach ($data->getRepository() as $value_1) {
                $values_1[] = $this->normalizer->normalize($value_1, 'json', $context);
            }
            $dataArray['repository'] = $values_1;
        }

        return $dataArray;
    }

    public function getSupportedTypes(?string $format = null): array
    {
        return [\Flownative\Harbor\Api\Model\Search::class => false];
    }
}
