<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Scottbass3\Harbor\Api\Normalizer;

use Scottbass3\Harbor\Api\Runtime\Normalizer\CheckArray;
use Scottbass3\Harbor\Api\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class WebhookTargetObjectNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;

    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \Scottbass3\Harbor\Api\Model\WebhookTargetObject::class;
    }

    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && get_class($data) === \Scottbass3\Harbor\Api\Model\WebhookTargetObject::class;
    }

    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \Scottbass3\Harbor\Api\Model\WebhookTargetObject();
        if (\array_key_exists('skip_cert_verify', $data) && \is_int($data['skip_cert_verify'])) {
            $data['skip_cert_verify'] = (bool) $data['skip_cert_verify'];
        }
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('type', $data) && $data['type'] !== null) {
            $object->setType($data['type']);
        } elseif (\array_key_exists('type', $data) && $data['type'] === null) {
            $object->setType(null);
        }
        if (\array_key_exists('address', $data) && $data['address'] !== null) {
            $object->setAddress($data['address']);
        } elseif (\array_key_exists('address', $data) && $data['address'] === null) {
            $object->setAddress(null);
        }
        if (\array_key_exists('auth_header', $data) && $data['auth_header'] !== null) {
            $object->setAuthHeader($data['auth_header']);
        } elseif (\array_key_exists('auth_header', $data) && $data['auth_header'] === null) {
            $object->setAuthHeader(null);
        }
        if (\array_key_exists('skip_cert_verify', $data) && $data['skip_cert_verify'] !== null) {
            $object->setSkipCertVerify($data['skip_cert_verify']);
        } elseif (\array_key_exists('skip_cert_verify', $data) && $data['skip_cert_verify'] === null) {
            $object->setSkipCertVerify(null);
        }
        if (\array_key_exists('payload_format', $data) && $data['payload_format'] !== null) {
            $object->setPayloadFormat($data['payload_format']);
        } elseif (\array_key_exists('payload_format', $data) && $data['payload_format'] === null) {
            $object->setPayloadFormat(null);
        }

        return $object;
    }

    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        $dataArray = [];
        if ($data->isInitialized('type') && null !== $data->getType()) {
            $dataArray['type'] = $data->getType();
        }
        if ($data->isInitialized('address') && null !== $data->getAddress()) {
            $dataArray['address'] = $data->getAddress();
        }
        if ($data->isInitialized('authHeader') && null !== $data->getAuthHeader()) {
            $dataArray['auth_header'] = $data->getAuthHeader();
        }
        if ($data->isInitialized('skipCertVerify') && null !== $data->getSkipCertVerify()) {
            $dataArray['skip_cert_verify'] = $data->getSkipCertVerify();
        }
        if ($data->isInitialized('payloadFormat') && null !== $data->getPayloadFormat()) {
            $dataArray['payload_format'] = $data->getPayloadFormat();
        }

        return $dataArray;
    }

    public function getSupportedTypes(?string $format = null): array
    {
        return [\Scottbass3\Harbor\Api\Model\WebhookTargetObject::class => false];
    }
}
