<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Harbor\Api\Model;

class AuditLog
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The ID of the audit log entry.
     *
     * @var int|null
     */
    protected $id;
    /**
     * Username of the user in this log entry.
     *
     * @var string|null
     */
    protected $username;
    /**
     * Name of the repository in this log entry.
     *
     * @var string|null
     */
    protected $resource;
    /**
     * Tag of the repository in this log entry.
     *
     * @var string|null
     */
    protected $resourceType;
    /**
     * The operation against the repository in this log entry.
     *
     * @var string|null
     */
    protected $operation;
    /**
     * The time when this operation is triggered.
     *
     * @var \DateTimeInterface|null
     */
    protected $opTime;

    /**
     * The ID of the audit log entry.
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * The ID of the audit log entry.
     */
    public function setId(?int $id): self
    {
        $this->initialized['id'] = true;
        $this->id = $id;

        return $this;
    }

    /**
     * Username of the user in this log entry.
     */
    public function getUsername(): ?string
    {
        return $this->username;
    }

    /**
     * Username of the user in this log entry.
     */
    public function setUsername(?string $username): self
    {
        $this->initialized['username'] = true;
        $this->username = $username;

        return $this;
    }

    /**
     * Name of the repository in this log entry.
     */
    public function getResource(): ?string
    {
        return $this->resource;
    }

    /**
     * Name of the repository in this log entry.
     */
    public function setResource(?string $resource): self
    {
        $this->initialized['resource'] = true;
        $this->resource = $resource;

        return $this;
    }

    /**
     * Tag of the repository in this log entry.
     */
    public function getResourceType(): ?string
    {
        return $this->resourceType;
    }

    /**
     * Tag of the repository in this log entry.
     */
    public function setResourceType(?string $resourceType): self
    {
        $this->initialized['resourceType'] = true;
        $this->resourceType = $resourceType;

        return $this;
    }

    /**
     * The operation against the repository in this log entry.
     */
    public function getOperation(): ?string
    {
        return $this->operation;
    }

    /**
     * The operation against the repository in this log entry.
     */
    public function setOperation(?string $operation): self
    {
        $this->initialized['operation'] = true;
        $this->operation = $operation;

        return $this;
    }

    /**
     * The time when this operation is triggered.
     */
    public function getOpTime(): ?\DateTimeInterface
    {
        return $this->opTime;
    }

    /**
     * The time when this operation is triggered.
     */
    public function setOpTime(?\DateTimeInterface $opTime): self
    {
        $this->initialized['opTime'] = true;
        $this->opTime = $opTime;

        return $this;
    }
}
