<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Harbor\Api\Model;

class LdapFailedImportUser
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * the uid can't add to system.
     *
     * @var string|null
     */
    protected $uid;
    /**
     * fail reason.
     *
     * @var string|null
     */
    protected $error;

    /**
     * the uid can't add to system.
     */
    public function getUid(): ?string
    {
        return $this->uid;
    }

    /**
     * the uid can't add to system.
     */
    public function setUid(?string $uid): self
    {
        $this->initialized['uid'] = true;
        $this->uid = $uid;

        return $this;
    }

    /**
     * fail reason.
     */
    public function getError(): ?string
    {
        return $this->error;
    }

    /**
     * fail reason.
     */
    public function setError(?string $error): self
    {
        $this->initialized['error'] = true;
        $this->error = $error;

        return $this;
    }
}
