<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Harbor\Api\Model;

class LdapPingResult
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Test success.
     *
     * @var bool|null
     */
    protected $success;
    /**
     * The ping operation output message.
     *
     * @var string|null
     */
    protected $message;

    /**
     * Test success.
     */
    public function getSuccess(): ?bool
    {
        return $this->success;
    }

    /**
     * Test success.
     */
    public function setSuccess(?bool $success): self
    {
        $this->initialized['success'] = true;
        $this->success = $success;

        return $this;
    }

    /**
     * The ping operation output message.
     */
    public function getMessage(): ?string
    {
        return $this->message;
    }

    /**
     * The ping operation output message.
     */
    public function setMessage(?string $message): self
    {
        $this->initialized['message'] = true;
        $this->message = $message;

        return $this;
    }
}
