<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Harbor\Api\Model;

class Metadata
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * id.
     *
     * @var string|null
     */
    protected $id;
    /**
     * name.
     *
     * @var string|null
     */
    protected $name;
    /**
     * icon.
     *
     * @var string|null
     */
    protected $icon;
    /**
     * maintainers.
     *
     * @var list<string>|null
     */
    protected $maintainers;
    /**
     * version.
     *
     * @var string|null
     */
    protected $version;
    /**
     * source.
     *
     * @var string|null
     */
    protected $source;

    /**
     * id.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * id.
     */
    public function setId(?string $id): self
    {
        $this->initialized['id'] = true;
        $this->id = $id;

        return $this;
    }

    /**
     * name.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * name.
     */
    public function setName(?string $name): self
    {
        $this->initialized['name'] = true;
        $this->name = $name;

        return $this;
    }

    /**
     * icon.
     */
    public function getIcon(): ?string
    {
        return $this->icon;
    }

    /**
     * icon.
     */
    public function setIcon(?string $icon): self
    {
        $this->initialized['icon'] = true;
        $this->icon = $icon;

        return $this;
    }

    /**
     * maintainers.
     *
     * @return list<string>|null
     */
    public function getMaintainers(): ?array
    {
        return $this->maintainers;
    }

    /**
     * maintainers.
     *
     * @param list<string>|null $maintainers
     */
    public function setMaintainers(?array $maintainers): self
    {
        $this->initialized['maintainers'] = true;
        $this->maintainers = $maintainers;

        return $this;
    }

    /**
     * version.
     */
    public function getVersion(): ?string
    {
        return $this->version;
    }

    /**
     * version.
     */
    public function setVersion(?string $version): self
    {
        $this->initialized['version'] = true;
        $this->version = $version;

        return $this;
    }

    /**
     * source.
     */
    public function getSource(): ?string
    {
        return $this->source;
    }

    /**
     * source.
     */
    public function setSource(?string $source): self
    {
        $this->initialized['source'] = true;
        $this->source = $source;

        return $this;
    }
}
