<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Harbor\Api\Model;

class Platform
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The architecture that the artifact applys to.
     *
     * @var string|null
     */
    protected $architecture;
    /**
     * The OS that the artifact applys to.
     *
     * @var string|null
     */
    protected $os;
    /**
     * The version of the OS that the artifact applys to.
     *
     * @var string|null
     */
    protected $osVersion;
    /**
     * The features of the OS that the artifact applys to.
     *
     * @var list<string>|null
     */
    protected $osFeatures;
    /**
     * The variant of the CPU.
     *
     * @var string|null
     */
    protected $variant;

    /**
     * The architecture that the artifact applys to.
     */
    public function getArchitecture(): ?string
    {
        return $this->architecture;
    }

    /**
     * The architecture that the artifact applys to.
     */
    public function setArchitecture(?string $architecture): self
    {
        $this->initialized['architecture'] = true;
        $this->architecture = $architecture;

        return $this;
    }

    /**
     * The OS that the artifact applys to.
     */
    public function getOs(): ?string
    {
        return $this->os;
    }

    /**
     * The OS that the artifact applys to.
     */
    public function setOs(?string $os): self
    {
        $this->initialized['os'] = true;
        $this->os = $os;

        return $this;
    }

    /**
     * The version of the OS that the artifact applys to.
     */
    public function getOsVersion(): ?string
    {
        return $this->osVersion;
    }

    /**
     * The version of the OS that the artifact applys to.
     */
    public function setOsVersion(?string $osVersion): self
    {
        $this->initialized['osVersion'] = true;
        $this->osVersion = $osVersion;

        return $this;
    }

    /**
     * The features of the OS that the artifact applys to.
     *
     * @return list<string>|null
     */
    public function getOsFeatures(): ?array
    {
        return $this->osFeatures;
    }

    /**
     * The features of the OS that the artifact applys to.
     *
     * @param list<string>|null $osFeatures
     */
    public function setOsFeatures(?array $osFeatures): self
    {
        $this->initialized['osFeatures'] = true;
        $this->osFeatures = $osFeatures;

        return $this;
    }

    /**
     * The variant of the CPU.
     */
    public function getVariant(): ?string
    {
        return $this->variant;
    }

    /**
     * The variant of the CPU.
     */
    public function setVariant(?string $variant): self
    {
        $this->initialized['variant'] = true;
        $this->variant = $variant;

        return $this;
    }
}
