<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Scottbass3\Harbor\Api\Model;

class ProjectDeletable
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Whether the project can be deleted.
     *
     * @var bool|null
     */
    protected $deletable;
    /**
     * The detail message when the project can not be deleted.
     *
     * @var string|null
     */
    protected $message;

    /**
     * Whether the project can be deleted.
     */
    public function getDeletable(): ?bool
    {
        return $this->deletable;
    }

    /**
     * Whether the project can be deleted.
     */
    public function setDeletable(?bool $deletable): self
    {
        $this->initialized['deletable'] = true;
        $this->deletable = $deletable;

        return $this;
    }

    /**
     * The detail message when the project can not be deleted.
     */
    public function getMessage(): ?string
    {
        return $this->message;
    }

    /**
     * The detail message when the project can not be deleted.
     */
    public function setMessage(?string $message): self
    {
        $this->initialized['message'] = true;
        $this->message = $message;

        return $this;
    }
}
