<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Harbor\Api\Model;

class RegistryProviderInfo
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The registry endpoint pattern.
     *
     * @var RegistryProviderEndpointPattern|null
     */
    protected $endpointPattern;
    /**
     * The registry credential pattern.
     *
     * @var RegistryProviderCredentialPattern|null
     */
    protected $credentialPattern;

    /**
     * The registry endpoint pattern.
     */
    public function getEndpointPattern(): ?RegistryProviderEndpointPattern
    {
        return $this->endpointPattern;
    }

    /**
     * The registry endpoint pattern.
     */
    public function setEndpointPattern(?RegistryProviderEndpointPattern $endpointPattern): self
    {
        $this->initialized['endpointPattern'] = true;
        $this->endpointPattern = $endpointPattern;

        return $this;
    }

    /**
     * The registry credential pattern.
     */
    public function getCredentialPattern(): ?RegistryProviderCredentialPattern
    {
        return $this->credentialPattern;
    }

    /**
     * The registry credential pattern.
     */
    public function setCredentialPattern(?RegistryProviderCredentialPattern $credentialPattern): self
    {
        $this->initialized['credentialPattern'] = true;
        $this->credentialPattern = $credentialPattern;

        return $this;
    }
}
