<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Scottbass3\Harbor\Api\Model;

class RetentionSelectorMetadata
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string|null
     */
    protected $displayText;
    /**
     * @var string|null
     */
    protected $kind;
    /**
     * @var list<string>|null
     */
    protected $decorations;

    public function getDisplayText(): ?string
    {
        return $this->displayText;
    }

    public function setDisplayText(?string $displayText): self
    {
        $this->initialized['displayText'] = true;
        $this->displayText = $displayText;

        return $this;
    }

    public function getKind(): ?string
    {
        return $this->kind;
    }

    public function setKind(?string $kind): self
    {
        $this->initialized['kind'] = true;
        $this->kind = $kind;

        return $this;
    }

    /**
     * @return list<string>|null
     */
    public function getDecorations(): ?array
    {
        return $this->decorations;
    }

    /**
     * @param list<string>|null $decorations
     */
    public function setDecorations(?array $decorations): self
    {
        $this->initialized['decorations'] = true;
        $this->decorations = $decorations;

        return $this;
    }
}
