<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Harbor\Api\Model;

class RetentionPolicy
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var int|null
     */
    protected $id;
    /**
     * @var string|null
     */
    protected $algorithm;
    /**
     * @var list<RetentionRule>|null
     */
    protected $rules;
    /**
     * @var RetentionRuleTrigger|null
     */
    protected $trigger;
    /**
     * @var RetentionPolicyScope|null
     */
    protected $scope;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id): self
    {
        $this->initialized['id'] = true;
        $this->id = $id;

        return $this;
    }

    public function getAlgorithm(): ?string
    {
        return $this->algorithm;
    }

    public function setAlgorithm(?string $algorithm): self
    {
        $this->initialized['algorithm'] = true;
        $this->algorithm = $algorithm;

        return $this;
    }

    /**
     * @return list<RetentionRule>|null
     */
    public function getRules(): ?array
    {
        return $this->rules;
    }

    /**
     * @param list<RetentionRule>|null $rules
     */
    public function setRules(?array $rules): self
    {
        $this->initialized['rules'] = true;
        $this->rules = $rules;

        return $this;
    }

    public function getTrigger(): ?RetentionRuleTrigger
    {
        return $this->trigger;
    }

    public function setTrigger(?RetentionRuleTrigger $trigger): self
    {
        $this->initialized['trigger'] = true;
        $this->trigger = $trigger;

        return $this;
    }

    public function getScope(): ?RetentionPolicyScope
    {
        return $this->scope;
    }

    public function setScope(?RetentionPolicyScope $scope): self
    {
        $this->initialized['scope'] = true;
        $this->scope = $scope;

        return $this;
    }
}
