<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Harbor\Api\Model;

class ScanDataExportJob
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The id of the scan data export job.
     *
     * @var int|null
     */
    protected $id;

    /**
     * The id of the scan data export job.
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * The id of the scan data export job.
     */
    public function setId(?int $id): self
    {
        $this->initialized['id'] = true;
        $this->id = $id;

        return $this;
    }
}
