<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Scottbass3\Harbor\Api\Model;

class SchedulerStatus
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * if the scheduler is paused.
     *
     * @var bool|null
     */
    protected $paused;

    /**
     * if the scheduler is paused.
     */
    public function getPaused(): ?bool
    {
        return $this->paused;
    }

    /**
     * if the scheduler is paused.
     */
    public function setPaused(?bool $paused): self
    {
        $this->initialized['paused'] = true;
        $this->paused = $paused;

        return $this;
    }
}
