<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Flownative\Harbor\Api\Model;

class UserGroup
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The ID of the user group.
     *
     * @var int
     */
    protected $id;
    /**
     * The name of the user group.
     *
     * @var string
     */
    protected $groupName;
    /**
     * The group type, 1 for LDAP group, 2 for HTTP group, 3 for OIDC group.
     *
     * @var int
     */
    protected $groupType;
    /**
     * The DN of the LDAP group if group type is 1 (LDAP group).
     *
     * @var string
     */
    protected $ldapGroupDn;

    /**
     * The ID of the user group.
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * The ID of the user group.
     */
    public function setId(int $id): self
    {
        $this->initialized['id'] = true;
        $this->id = $id;

        return $this;
    }

    /**
     * The name of the user group.
     */
    public function getGroupName(): string
    {
        return $this->groupName;
    }

    /**
     * The name of the user group.
     */
    public function setGroupName(string $groupName): self
    {
        $this->initialized['groupName'] = true;
        $this->groupName = $groupName;

        return $this;
    }

    /**
     * The group type, 1 for LDAP group, 2 for HTTP group, 3 for OIDC group.
     */
    public function getGroupType(): int
    {
        return $this->groupType;
    }

    /**
     * The group type, 1 for LDAP group, 2 for HTTP group, 3 for OIDC group.
     */
    public function setGroupType(int $groupType): self
    {
        $this->initialized['groupType'] = true;
        $this->groupType = $groupType;

        return $this;
    }

    /**
     * The DN of the LDAP group if group type is 1 (LDAP group).
     */
    public function getLdapGroupDn(): string
    {
        return $this->ldapGroupDn;
    }

    /**
     * The DN of the LDAP group if group type is 1 (LDAP group).
     */
    public function setLdapGroupDn(string $ldapGroupDn): self
    {
        $this->initialized['ldapGroupDn'] = true;
        $this->ldapGroupDn = $ldapGroupDn;

        return $this;
    }
}
